.TH "Referência do diretório sha" 3 "Domingo, 23 de Outubro de 2016" "Version 1.0" "HomeStark_6LoWPAN_Device" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório sha \- 
.SH SYNOPSIS
.br
.PP
.SS "Ficheiros"

.in +1c
.ti -1c
.RI "ficheiro \fBsha256\&.c\fP"
.br
.ti -1c
.RI "ficheiro \fBsha256\&.h\fP"
.br
.ti -1c
.RI "ficheiro \fBsha256_example\&.c\fP"
.br
.in -1c
