.TH "Referência do diretório CoAP" 3 "Quinta, 29 de Setembro de 2016" "Version 1.0" "HomeStark_6LoWPAN_Device" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referência do diretório CoAP \- 
.SH SYNOPSIS
.br
.PP
.SS "Ficheiros"

.in +1c
.ti -1c
.RI "ficheiro \fBcoap-server\&.c\fP"
.br
.ti -1c
.RI "ficheiro \fBcoap-server\&.h\fP"
.br
.in -1c
