.TH "main_core.c" 3 "Quinta, 29 de Setembro de 2016" "Version 1.0" "HomeStark_6LoWPAN_Device" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main_core.c \- 
.PP
Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'contiki\&.h'\fP
.br
\fC#include 'contiki-lib\&.h'\fP
.br
\fC#include 'contiki-net\&.h'\fP
.br
\fC#include 'rest-engine\&.h'\fP
.br
\fC#include 'coap-server\&.h'\fP
.br
\fC#include 'net/ipv6/uip-ds6\&.h'\fP
.br
\fC#include 'net/ip/uip\&.h'\fP
.br
\fC#include 'net/rpl/rpl\&.h'\fP
.br
\fC#include 'snmp\&.h'\fP
.br
\fC#include 'mibii\&.h'\fP
.br

.SS "Funções"

.in +1c
.ti -1c
.RI "\fBPROCESS\fP (init_system_process,'[Contiki-OS] Starting the OS')"
.br
.ti -1c
.RI "\fBPROCESS_THREAD\fP (init_system_process, ev, data)"
.br
.in -1c
.SS "Variáveis"

.in +1c
.ti -1c
.RI "AUTOSTART_PROCESSES & \fBinit_system_process\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements\&. 

See the NOTICE file distributed with this work for additional information regarding copyright ownership\&. The ASF licenses this file to you under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at
.PP
http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&.
.PP
This project is delivered under APACHE 2\&.0\&.
.PP
\fBAutor:\fP
.RS 4
Ânderson Ignácio da Silva 
.RE
.PP
\fBData:\fP
.RS 4
19 Ago 2016 Main file for HomeStark devices - 6LoWPAN 
.RE
.PP
\fBVeja também:\fP
.RS 4
http://www.aignacio.com 
.RE
.PP

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para HomeStark_6LoWPAN_Device a partir do código fonte\&.
