.TH "oid_data" 3 "Quinta, 29 de Setembro de 2016" "Version 1.0" "HomeStark_6LoWPAN_Device" \" -*- nroff -*-
.ad l
.nh
.SH NAME
oid_data \- 
.PP
Struct of OID data in MIB Implementation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mibii\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "uint8_t \fBoid_tree\fP [2]"
.br
.RI "\fIOID tree value in the MIB\&. \fP"
.ti -1c
.RI "char \fBoid_value\fP [MAX_STRINGS_LENGTH]"
.br
.RI "\fIOID Data in the tree MIB Implementation\&. \fP"
.in -1c
.SH "Descrição detalhada"
.PP 
Struct of OID data in MIB Implementation\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para HomeStark_6LoWPAN_Device a partir do código fonte\&.
