.TH "project-conf.h" 3 "Quinta, 29 de Setembro de 2016" "Version 1.0" "HomeStark_6LoWPAN_Device" \" -*- nroff -*-
.ad l
.nh
.SH NAME
project-conf.h \- 
.PP

.PP
.nf
 Erbium (Er) example project configuration.
.fi
.PP
  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNETSTACK_CONF_RDC\fP   contikimac_driver"
.br
.ti -1c
.RI "#define \fBRPL_CONF_MAX_DAG_PER_INSTANCE\fP   1"
.br
.ti -1c
.RI "#define \fBUIP_CONF_TCP\fP   0"
.br
.ti -1c
.RI "#define \fBNETSTACK_CONF_MAC\fP   nullmac_driver"
.br
.ti -1c
.RI "#define \fBREST_MAX_CHUNK_SIZE\fP   48"
.br
.ti -1c
.RI "#define \fBCOAP_MAX_OPEN_TRANSACTIONS\fP   4"
.br
.ti -1c
.RI "#define \fBCOAP_LINK_FORMAT_FILTERING\fP   0"
.br
.ti -1c
.RI "#define \fBCOAP_PROXY_OPTION_PROCESSING\fP   0"
.br
.ti -1c
.RI "#define \fBRPL_CONF_WITH_DAO_ACK\fP   0"
.br
.ti -1c
.RI "#define \fBRPL_CONF_OF\fP   rpl_of0"
.br
.ti -1c
.RI "#define \fBCOAP_OBSERVE_CLIENT\fP   1"
.br
.in -1c
.SH "Descrição detalhada"
.PP 

.PP
.nf
 Erbium (Er) example project configuration.
.fi
.PP
 


.PP
\fBAutor:\fP
.RS 4
Matthias Kovatsch kovatsch@inf.ethz.ch 
.RE
.PP

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para HomeStark_6LoWPAN_Device a partir do código fonte\&.
