.TH "request" 3 "Quinta, 29 de Setembro de 2016" "Version 1.0" "HomeStark_6LoWPAN_Device" \" -*- nroff -*-
.ad l
.nh
.SH NAME
request \- 
.PP
Struct for request of SNMP Packets\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <snmp\&.h>\fP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "\fBsnmp_t\fP \fBpdu_request\fP"
.br
.ti -1c
.RI "struct \fBrequest\fP * \fBlink\fP"
.br
.RI "\fILink to the next request\&. \fP"
.in -1c
.SH "Descrição detalhada"
.PP 
Struct for request of SNMP Packets\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para HomeStark_6LoWPAN_Device a partir do código fonte\&.
