.TH "SHA256_CTX" 3 "Domingo, 23 de Outubro de 2016" "Version 1.0" "HomeStark_6LoWPAN_Device" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SHA256_CTX \- 
.SH SYNOPSIS
.br
.PP
.SS "Campos de Dados"

.in +1c
.ti -1c
.RI "uchar \fBdata\fP [64]"
.br
.ti -1c
.RI "uint \fBdatalen\fP"
.br
.ti -1c
.RI "uint \fBbitlen\fP [2]"
.br
.ti -1c
.RI "uint \fBstate\fP [8]"
.br
.in -1c

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para HomeStark_6LoWPAN_Device a partir do código fonte\&.
