.TH "snmpd/snmp_asn1.c" 3 "Quinta, 29 de Setembro de 2016" "Version 1.0" "HomeStark_6LoWPAN_Device" \" -*- nroff -*-
.ad l
.nh
.SH NAME
snmpd/snmp_asn1.c \- 
.PP
Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'snmp\&.h'\fP
.br
\fC#include 'mibii\&.h'\fP
.br

.SS "Funções"

.in +1c
.ti -1c
.RI "\fBresp_con_t\fP \fBerror_check_snmp\fP (uint8_t *error_data)"
.br
.ti -1c
.RI "\fBresp_con_t\fP \fBdecode_asn1_oct_str\fP (uint8_t *data_encoded, uint8_t *oct_str)"
.br
.RI "\fISNMP Decode Octet String\&. \fP"
.ti -1c
.RI "\fBresp_con_t\fP \fBdecode_asn1_integer\fP (uint8_t *data_encoded, uint32_t *integer_value)"
.br
.RI "\fISNMP Decode Integer\&. \fP"
.ti -1c
.RI "\fBresp_con_t\fP \fBsnmp_decode_message\fP (char *snmp_packet, \fBsnmp_t\fP *snmp_handle)"
.br
.RI "\fIDecode SNMP message\&. \fP"
.ti -1c
.RI "uint16_t \fBsnmp_encode_message\fP (\fBsnmp_t\fP *snmp_handle, char *data_encoded)"
.br
.RI "\fIEncode SNMP message\&. \fP"
.ti -1c
.RI "uint16_t \fBsnmp_encode_trap\fP (uint8_t *trap_pdu, uint8_t type_trap, uint8_t heartbeat)"
.br
.RI "\fIEncode a SNMPv1 Trap message\&. \fP"
.in -1c
.SH "Descrição detalhada"
.PP 
Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements\&. 

See the NOTICE file distributed with this work for additional information regarding copyright ownership\&. The ASF licenses this file to you under the Apache License, Version 2\&.0 (the 'License'); you may not use this file except in compliance with the License\&. You may obtain a copy of the License at
.PP
http://www.apache.org/licenses/LICENSE-2.0
.PP
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\&. See the License for the specific language governing permissions and limitations under the License\&.
.PP
This project is under APACHE 2\&.0 license\&.
.PP
Encoding and decoding functions to SNMP agent 
.PP
\fBAutor:\fP
.RS 4
Ânderson Ignácio da Silva 
.RE
.PP
\fBData:\fP
.RS 4
19 Sept 2016 
.RE
.PP
\fBVeja também:\fP
.RS 4
http://www.aignacio.com 
.RE
.PP

.SH "Documentação das funções"
.PP 
.SS "\fBresp_con_t\fP decode_asn1_integer (uint8_t *data_encoded, uint32_t *integer_value)"

.PP
SNMP Decode Integer\&. Decode ASN\&.1 integer(32 bit value)\&.
.PP
\fBParâmetros:\fP
.RS 4
\fIdata_encoded\fP Data do decode 
.br
\fIinteger_value\fP Variable the will receive the integer 32-bit
.RE
.PP
\fBValores retornados:\fP
.RS 4
\fISUCCESS_CON\fP Success to decode integer 
.br
\fIFAIL_CON\fP Fail to decode integer 
.RE
.PP

.PP
.nf
91                                                                               {
92   uint8_t length = (intptr_t)*(data_encoded+1);
93   // uint32_t integer_value;
94   size_t i = 0;
95   uint32_t aux;
96 
97   // Test if it's an integer value to be decoded
98   if (*data_encoded != ASN1_PRIM_INTEGER){
99     debug_snmp("The value is not integer!");
100     return FAIL_CON;
101   }
102 
103   for (i=1, *integer_value = 0; i <= length; i++){
104     aux = *(data_encoded+1+i);
105     *integer_value += aux*(pow(256,(length-i)));
106     // debug_snmp("%lu * 256^%d = %lu",aux,(length-i),*integer_value);
107   }
108   return SUCCESS_CON;
109 }
.fi
.SS "\fBresp_con_t\fP decode_asn1_oct_str (uint8_t *data_encoded, uint8_t *oct_str)"

.PP
SNMP Decode Octet String\&. Decode Octet String in ASN\&.1 format\&.
.PP
\fBParâmetros:\fP
.RS 4
\fIdata_encoded\fP Data do decode 
.br
\fIoct_str\fP Variable the will receive the octet string
.RE
.PP
\fBValores retornados:\fP
.RS 4
\fISUCCESS_CON\fP Success to decode string octet 
.br
\fIFAIL_CON\fP Fail to decode octet string 
.RE
.PP

.PP
.nf
72                                                                        {
73   if (*data_encoded !=  (intptr_t)ASN1_PRIM_OCT_STR) {
74     debug_snmp("The type of value passed is not an octet string!");
75     return FAIL_CON;
76   }
77 
78   uint8_t length = (intptr_t)*(data_encoded+1),
79           index = 0;
80   while (length) {
81     *(oct_str+index) = (intptr_t)*(data_encoded+2+index);
82     length--;
83     index++;
84   }
85 
86   *(oct_str+index) = '\0';
87   // printf("\nEndereco----:> %d\n",oct_str);
88   return SUCCESS_CON;
89 }
.fi
.SS "\fBresp_con_t\fP snmp_decode_message (char *snmp_packet, \fBsnmp_t\fP *v)"

.PP
Decode SNMP message\&. Decode a SNMP message v1 and format to answer request\&.
.PP
\fBParâmetros:\fP
.RS 4
\fIsnmp_packet\fP Data UDP - SNMP to decode 
.br
\fIsnmp_handle\fP Struct that will receive the SNMP request messsage
.RE
.PP
\fBValores retornados:\fP
.RS 4
\fISUCCESS_CON\fP Success to decode SNMP Message 
.br
\fIFAIL_CON\fP Fail to decode SNMP Message 
.RE
.PP

.PP
.nf
111                                                                       {
112   uint8_t buffer[50], aux;
113   size_t i;
114 
115   #ifdef DEBUG_SNMP_DECODING
116   // debug_snmp("Encoded SNMP packet:\n\t");
117   // for (i=0, j=0; i < *(snmp_packet+1)+1; j++, i++){
118   //   if (j > 7){
119   //     j = 0;
120   //     printf("\n\t");
121   //   }
122   //   printf("[%02x] ",*(snmp_packet+i));
123   // }
124   #endif
125 
126   if (!check_seq(*snmp_packet)){
127     debug_snmp("Sequence initial of SNMP message error:%x",*snmp_packet);
128     return FAIL_CON;
129   }
130 
131   /************************ Check the SNMP version ****************************/
132   for (i=0;i < *(snmp_packet+3)+2; i++)
133     buffer[i] = *(snmp_packet+2+i);
134   uint32_t SNMPv = 0;
135   if (!decode_asn1_integer(buffer,&SNMPv)) return FAIL_CON;
136   #ifdef DEBUG_SNMP_DECODING
137   debug_snmp("Version SNMP:[1] OK");
138   #endif
139   if (SNMPv != SNMP_VERSION_1) {
140     debug_snmp("SNMP version is different from v1:%lu",SNMPv);
141     return FAIL_CON;
142   }
143   snmp_handle->snmp_version = SNMPv;
144 
145   /********************** Get the community string ****************************/
146   for (i=0;i < *(snmp_packet+6)+2; i++)
147   snmp_handle->community[i] = *(snmp_packet+5+i);
148   snmp_handle->community[i] = '\0';
149   aux = i;
150   #ifdef DEBUG_SNMP_DECODING
151   debug_snmp("Community String: ");
152   for (i=0; i < aux; i++){
153     if (i<2)
154       printf("[%d]",snmp_handle->community[i]);
155     else
156       printf("[%c]",snmp_handle->community[i]);
157   }
158   #endif
159 
160   /************************** Get the request ID ******************************/
161   aux = 5+snmp_handle->community[1]+2+2;
162   for (i=0;i < *(snmp_packet+aux+1)+2; i++)
163     snmp_handle->request_id_c[i] = *(snmp_packet+aux+i);
164   snmp_handle->request_id_c[i] = '\0';
165   aux = i;
166   #ifdef DEBUG_SNMP_DECODING
167   debug_snmp("Request ID: ");
168   for (i=0; i < aux; i++){
169     if (i<2)
170       printf("[%d]",snmp_handle->request_id_c[i]);
171     else
172     printf("[%x]",snmp_handle->request_id_c[i]);
173   }
174   #endif
175 
176   /************************** Check for errors ********************************/
177   aux = 5+(snmp_handle->community[1]+2)+2+(snmp_handle->request_id_c[1]+2);
178   for (i=0;i < 6; i++)
179     buffer[i] = *(snmp_packet+aux+i);
180   buffer[i] = '\0';
181   error_check_snmp(buffer);
182 
183   /**************************** Get the OID ***********************************/
184   aux = 5+(snmp_handle->community[1]+2);
185   aux += 2+(snmp_handle->request_id_c[1]+2)+10;
186   for (i=0;i < *(snmp_packet+aux+1)+2; i++)
187     snmp_handle->oid_encoded[i] = *(snmp_packet+aux+i);
188   snmp_handle->oid_encoded[i] = '\0';
189   aux = i;
190   #ifdef DEBUG_SNMP_DECODING
191   debug_snmp("OID: ");
192   for (i=0; i < aux; i++){
193     if (i <= 1)
194       printf("[%d]",snmp_handle->oid_encoded[i]);
195     else if (i == 2)
196       printf("[%d\&.",snmp_handle->oid_encoded[i]);
197     else
198     printf("%d\&.",snmp_handle->oid_encoded[i]);
199   }
200   printf("]");
201   #endif
202 
203   /************************** Get the PDU type ********************************/
204   aux = 5+(snmp_handle->community[1]+2);
205   snmp_handle->request_type  = *(snmp_packet+aux);
206   snmp_handle->response_type = ASN1_CPX_GET_RESP;
207 
208   uint8_t string_value[MAX_OCTET_STRING];
209   uint8_t status_mib2 = mib_ii_get_oid(snmp_handle->oid_encoded,&string_value[0]);
210 
211   switch (snmp_handle->request_type) {
212     case ASN1_CPX_SEQUENCE:
213     break;
214     case ASN1_CPX_GET_REQ:
215       aux = snmp_handle->oid_encoded[1]+1;
216       if (snmp_handle->oid_encoded[aux] != 0   ||
217           snmp_handle->oid_encoded[aux-3] != 1 ||
218           snmp_handle->oid_encoded[aux-4] != 2 ||
219           snmp_handle->oid_encoded[aux-5] != 1 ||
220           snmp_handle->oid_encoded[aux-6] != 6 ||
221           snmp_handle->oid_encoded[aux-7] != 0x2b){
222         snmp_handle->oid_encoded[aux] = 1;
223         status_mib2 = mib_ii_get_oid(snmp_handle->oid_encoded,&string_value[0]);
224       }
225       #ifdef DEBUG_SNMP_DECODING
226       debug_snmp("GET Request PDU Type");
227       #endif
228       if (!status_mib2){
229         #ifdef DEBUG_SNMP_DECODING
230         debug_snmp("There isn't an value for that OID!");
231         #endif
232         snmp_handle->value[0] = 0x05;
233         snmp_handle->value[1] = 0x00;
234       }
235       else {
236         aux = strlen((const char*)string_value);
237         snmp_handle->value[0] = ASN1_PRIM_OCT_STR;
238         snmp_handle->value[1] = aux;
239 
240         for (i = 0; i < aux; i++)
241           snmp_handle->value[2+i] = string_value[i];
242         #ifdef DEBUG_SNMP_DECODING
243         debug_snmp("String for OID: ");
244         for (i=0; i < aux+2; i++){
245           if (i == 0)
246             printf("[%x]",snmp_handle->value[i]);
247           else if (i == 1)
248             printf("[%d][",snmp_handle->value[i]);
249           else
250             printf("%c",snmp_handle->value[i]);
251         }
252         printf("]");
253         #endif
254       }
255     break;
256     case ASN1_CPX_NEXT_REQ:
257       // Let's check the last byte
258       aux = snmp_handle->oid_encoded[1]+1;
259       if (snmp_handle->oid_encoded[aux] == 0) {
260         // We need to increment the OID for the snmpwalk\&.\&.\&. requisition
261         if (snmp_handle->oid_encoded[aux-1] < 9) {
262           snmp_handle->oid_encoded[aux-1] = snmp_handle->oid_encoded[aux-1]+1;
263         }
264         else
265           snmp_handle->oid_encoded[aux] = 1; // Let's force not unknow value in the mib tree
266         status_mib2 = mib_ii_get_oid(snmp_handle->oid_encoded,&string_value[0]);
267       }
268       else{
269         if (snmp_handle->oid_encoded[aux-1] == 1 &&
270             snmp_handle->oid_encoded[aux-2] == 2 &&
271             snmp_handle->oid_encoded[aux-3] == 1 &&
272             snmp_handle->oid_encoded[aux-4] == 6 &&
273             snmp_handle->oid_encoded[aux-5] == 0x2b) {
274           snmp_handle->oid_encoded[1] += 2;
275           snmp_handle->oid_encoded[aux+1] = 1;
276           snmp_handle->oid_encoded[aux+2] = 0;
277           snmp_handle->oid_encoded[aux+3] = '\0';
278         }
279         // We need to set to the nearest OID for the snmpwalk\&.\&.\&. requisition, in this case \&.1\&.0
280         status_mib2 = mib_ii_get_oid(snmp_handle->oid_encoded,&string_value[0]);
281       }
282 
283       #ifdef DEBUG_SNMP_DECODING
284       debug_snmp("GET NEXT Request PDU Type");
285       #endif
286       if (!status_mib2){
287         #ifdef DEBUG_SNMP_DECODING
288         debug_snmp("There isn't an value for that OID!");
289         #endif
290         snmp_handle->value[0] = 0x05;
291         snmp_handle->value[1] = 0x00;
292       }
293       else {
294         aux = strlen((const char*)string_value);
295         snmp_handle->value[0] = ASN1_PRIM_OCT_STR;
296         snmp_handle->value[1] = aux;
297 
298         for (i = 0; i < aux; i++)
299           snmp_handle->value[2+i] = string_value[i];
300         #ifdef DEBUG_SNMP_DECODING
301         debug_snmp("String for OID: ");
302         for (i=0; i < aux+2; i++){
303           if (i == 0)
304             printf("[%x]",snmp_handle->value[i]);
305           else if (i == 1)
306             printf("[%d][",snmp_handle->value[i]);
307           else
308             printf("%c",snmp_handle->value[i]);
309         }
310         printf("]");
311         #endif
312       }
313     break;
314     case ASN1_CPX_GET_RESP:
315     break;
316     case ASN1_CPX_SET_REQ:
317     break;
318     default:
319       #ifdef DEBUG_SNMP_DECODING
320       debug_snmp("The PDU type is not know");
321       #endif
322       return FAIL_CON;
323     break;
324   }
325 
326   #ifdef DEBUG_SNMP_DECODING
327   printf("\n");
328   #endif
329   return SUCCESS_CON;
330 }
.fi
.SS "uint16_t snmp_encode_message (\fBsnmp_t\fP *snmp_handle, char *data_encoded)"

.PP
Encode SNMP message\&. Encode a SNMP message and format to send the answer\&.
.PP
\fBParâmetros:\fP
.RS 4
\fIsnmp_handle\fP Struct that will be encoded in the SNMP message format 
.br
\fIdata_encoded\fP Variable that'll receive the encoded SNMP Message
.RE
.PP
\fBValores retornados:\fP
.RS 4
\fIlength\fP Length of UDP packet encoded 
.RE
.PP

.PP
.nf
332                                                                      {
333   uint8_t i, aux = 0, aux2 = 0;
334   *data_encoded = ASN1_CPX_SEQUENCE;
335 
336   aux2 = 0;
337   aux2 += 3+(snmp_handle->community[1]+2)+12;
338   aux2 += (snmp_handle->request_id_c[1]+2);
339   aux2 += (snmp_handle->oid_encoded[1]+2);
340   aux2 += (snmp_handle->value[1]+2);
341   *(data_encoded+1) = aux2;
342 
343   *(data_encoded+2) = ASN1_PRIM_INTEGER;
344   *(data_encoded+3) = 0x01;
345   switch (snmp_handle->snmp_version) {
346     case SNMP_VERSION_1:
347       *(data_encoded+4) = SNMP_VERSION_1;
348     break;
349     case SNMP_VERSION_2C:
350       *(data_encoded+4) = SNMP_VERSION_2C;
351     break;
352     case SNMP_VERSION_3:
353       *(data_encoded+4) = SNMP_VERSION_3;
354     break;
355     default:
356       debug_snmp("Version SNMP not supported");
357       return FAIL_CON;
358     break;
359   }
360 
361   for ( i = 0; i < snmp_handle->community[1]+2; i++)
362     *(data_encoded+5+i) = snmp_handle->community[i];
363 
364   aux = 5+snmp_handle->community[1]+2;
365   *(data_encoded+aux) = ASN1_CPX_GET_RESP;
366 
367   aux2 = 0;
368   aux2 += (snmp_handle->request_id_c[1]+2)+10;
369   aux2 += (snmp_handle->oid_encoded[1]+2);
370   aux2 += (snmp_handle->value[1]+2);
371   *(data_encoded+aux+1) = aux2;
372 
373   aux += 2;
374   for ( i = 0; i < snmp_handle->request_id_c[1]+2; i++)
375     *(data_encoded+aux+i) = snmp_handle->request_id_c[i];
376 
377   aux += snmp_handle->request_id_c[1]+2;
378 
379   if (snmp_handle->value[0] == ASN1_PRIM_NULL) {
380     *(data_encoded+aux) = ASN1_PRIM_INTEGER;
381     aux++;
382     *(data_encoded+aux) = 0x01;
383     aux++;
384     *(data_encoded+aux) = ERROR_REQ_OID_NOT_FOUND;
385     aux++;
386     *(data_encoded+aux) = ASN1_PRIM_INTEGER;
387     aux++;
388     *(data_encoded+aux) = 0x01;
389     aux++;
390     *(data_encoded+aux) = ERROR_RESP_TOO_LARGE;
391     aux++;
392     *(data_encoded+aux) = ASN1_CPX_SEQUENCE;
393     aux++;
394     aux2 = 2;
395     aux2 += (snmp_handle->oid_encoded[1]+2);
396     aux2 += (snmp_handle->value[1]+2);
397     *(data_encoded+aux) = aux2;
398     aux++;
399     *(data_encoded+aux) = ASN1_CPX_SEQUENCE;
400     aux++;
401     aux2 = 0;
402     aux2 += (snmp_handle->oid_encoded[1]+2);
403     aux2 += (snmp_handle->value[1]+2);
404     *(data_encoded+aux) = aux2;
405     aux++;
406     for ( i = 0; i < snmp_handle->oid_encoded[1]+2; i++)
407       *(data_encoded+aux+i) = snmp_handle->oid_encoded[i];
408     aux += snmp_handle->oid_encoded[1]+2;
409     *(data_encoded+aux) = ASN1_PRIM_NULL;
410     aux++;
411     *(data_encoded+aux) = 0x00;
412   }
413   else{
414     *(data_encoded+aux) = ASN1_PRIM_INTEGER;
415     aux++;
416     *(data_encoded+aux) = 0x01;
417     aux++;
418     *(data_encoded+aux) = ERROR_NONE;
419     aux++;
420     *(data_encoded+aux) = ASN1_PRIM_INTEGER;
421     aux++;
422     *(data_encoded+aux) = 0x01;
423     aux++;
424     *(data_encoded+aux) = ERROR_NONE;
425     aux++;
426     *(data_encoded+aux) = ASN1_CPX_SEQUENCE;
427     aux++;
428     aux2 = 2;
429     aux2 += (snmp_handle->oid_encoded[1]+2);
430     aux2 += (snmp_handle->value[1]+2);
431     *(data_encoded+aux) = aux2;
432     aux++;
433     *(data_encoded+aux) = ASN1_CPX_SEQUENCE;
434     aux++;
435     aux2 = 0;
436     aux2 += (snmp_handle->oid_encoded[1]+2);
437     aux2 += (snmp_handle->value[1]+2);
438     *(data_encoded+aux) = aux2;
439     aux++;
440     for ( i = 0; i < snmp_handle->oid_encoded[1]+2; i++)
441       *(data_encoded+aux+i) = snmp_handle->oid_encoded[i];
442     aux += snmp_handle->oid_encoded[1]+2;
443     for ( i = 0; i < snmp_handle->value[1]+2; i++)
444       *(data_encoded+aux+i) = snmp_handle->value[i];
445   }
446   #ifdef DEBUG_SNMP_DECODING
447   debug_snmp("Len of encoded packet: %d",*(data_encoded+1)+1);
448   #endif
449   return *(data_encoded+1)+2;
450 }
.fi
.SS "uint16_t snmp_encode_trap (uint8_t *trap_pdu, uint8_ttype_trap, uint8_theartbeat)"

.PP
Encode a SNMPv1 Trap message\&. Encode a SNMPv1 Trap type message with AWGES PEN and heartbeat value
.PP
\fBParâmetros:\fP
.RS 4
\fItrap_pdu\fP Variable that'll receive the packet encoded 
.br
\fItype_trap\fP Type of trap that'll send ('coldStart','WarmStart'\&.\&.\&.) 
.br
\fIheartbeat\fP Heartbeat value of the node
.RE
.PP
\fBValores retornados:\fP
.RS 4
\fIlen\fP Length of encoded packet 
.RE
.PP

.PP
.nf
483                                                                                   {
484   // uint8_t i;//, aux = 0, aux2 = 0;
485   uint16_t length_trap = 0, aux = 0;
486 
487   *trap_pdu = ASN1_CPX_SEQUENCE;
488   *(trap_pdu+1) = 52+4;
489 
490   // SNMP Version
491   *(trap_pdu+2) = ASN1_PRIM_INTEGER;
492   *(trap_pdu+3) = 0x01;
493   *(trap_pdu+4) = SNMP_VERSION_1;
494 
495   // Comunity String - always "public"
496   *(trap_pdu+5) = ASN1_PRIM_OCT_STR;
497   *(trap_pdu+6) = 0x06;
498   *(trap_pdu+7) = 0x70;
499   *(trap_pdu+8) = 0x75;
500   *(trap_pdu+9) = 0x62;
501   *(trap_pdu+10) = 0x6c;
502   *(trap_pdu+11) = 0x69;
503   *(trap_pdu+12) = 0x63;
504 
505   // Type of PDU - Trap(0xa4)
506   *(trap_pdu+13) = ASN1_CPX_TRAP;
507   aux = 14;
508   *(trap_pdu+aux) = 39+4;
509 
510   // Enterprise OID - 0x06, 0x09, 0x2b, 0x06, 0x01, 0x04, 0x01, 0x04, 0x01, 0x02, 0x15
511   aux++;
512   *(trap_pdu+aux) = ASN1_PRIM_OID;
513   aux++;
514   *(trap_pdu+aux) = 0x09;
515   aux++;
516   *(trap_pdu+aux) = 0x2b;
517   aux++;
518   *(trap_pdu+aux) = 0x06;
519   aux++;
520   *(trap_pdu+aux) = 0x01;
521   aux++;
522   *(trap_pdu+aux) = 0x04;
523   aux++;
524   *(trap_pdu+aux) = 0x01;
525   aux++;
526   *(trap_pdu+aux) = 0x04;
527   aux++;
528   *(trap_pdu+aux) = 0x01;
529   aux++;
530   *(trap_pdu+aux) = 0x02;
531   aux++;
532   *(trap_pdu+aux) = 0x15;
533 
534   // IP Address of the agent, always 0\&.0\&.0\&.0 if we cannot send IPv6 in SNMPv1, in SNMPv2 the trap calls inform
535   aux++;
536   *(trap_pdu+aux) = ASN1_PRIM_IP_ADDRESS;
537   aux++;
538   *(trap_pdu+aux) = 4;
539   aux++;
540   *(trap_pdu+aux) = 0;
541   aux++;
542   *(trap_pdu+aux) = 0;
543   aux++;
544   *(trap_pdu+aux) = 0;
545   aux++;
546   *(trap_pdu+aux) = 0;
547 
548   // Generic Trap type
549   aux++;
550   *(trap_pdu+aux) = ASN1_PRIM_INTEGER;
551   aux++;
552   *(trap_pdu+aux) = 0x01;
553   aux++;
554   *(trap_pdu+aux) = type_trap;
555 
556   // Specific Trap Number - we don't use this
557   aux++;
558   *(trap_pdu+aux) = ASN1_PRIM_INTEGER;
559   aux++;
560   *(trap_pdu+aux) = 0x01;
561   aux++;
562   *(trap_pdu+aux) = 0x00;
563 
564   // Timestamp - we don't use this - default(0)
565   aux++;
566   *(trap_pdu+aux) = ASN1_PRIM_TIMESTAMP;
567   aux++;
568   *(trap_pdu+aux) = 0x01;
569   aux++;
570   *(trap_pdu+aux) = 0x00;
571 
572   // VarBind List - we don't use this - default(0)
573   aux++;
574   *(trap_pdu+aux) = ASN1_CPX_SEQUENCE;
575   aux++;
576   *(trap_pdu+aux) = 3+8+2+2;
577 
578   // VarBind List - we don't use this - default(0)
579   aux++;
580   *(trap_pdu+aux) = ASN1_CPX_SEQUENCE;
581   aux++;
582   *(trap_pdu+aux) = 3+8+2;
583 
584   // OID
585   aux++;
586   *(trap_pdu+aux) = ASN1_PRIM_OID;
587   aux++;
588   *(trap_pdu+aux) = 0x08;
589   aux++;
590   *(trap_pdu+aux) = 0x2b;
591   aux++;
592   *(trap_pdu+aux) = 0x06;
593   aux++;
594   *(trap_pdu+aux) = 0x01;
595   aux++;
596   *(trap_pdu+aux) = 0x02;
597   aux++;
598   *(trap_pdu+aux) = 0x01;
599   aux++;
600   *(trap_pdu+aux) = 0x02;
601   aux++;
602   *(trap_pdu+aux) = 0x01;
603   aux++;
604   *(trap_pdu+aux) = 0x00;
605 
606   // Value - Heartbeat
607   aux++;
608   *(trap_pdu+aux) = ASN1_PRIM_INTEGER;
609   aux++;
610   *(trap_pdu+aux) = 0x01;
611   aux++;
612   *(trap_pdu+aux) = heartbeat;
613 
614   length_trap = 54+4;
615   return length_trap;
616 }
.fi
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para HomeStark_6LoWPAN_Device a partir do código fonte\&.
